 const CategoriesUiData = [
    {
        id: 1,
        name: 'Electrician Services',
        Category: 'Electrician',
        image : '../images/Portfolio01.png',
        desc : 'Need An Electrician ?',
    },
    {
        id: 2,
        name: 'Pizza Shops',
        Category: 'Pizza Shops',
        image : '../images/Portfolio02.png',
        desc : 'Hungry Looking for Pizza ?',
    },
    {
        id: 3,
        name: 'Cab Services',
        Category: 'Cab/Car Services',
        image : '../images/Portfolio03.png',
        desc : 'Need An Cab Rider ?',
    },
    {
        id: 4,
        name: 'Coffe Shops',
        Category: 'Coffe Shops',
        image : '../images/Portfolio04.jpg',
        desc : 'Wanna Drink Coffe ?',
    },
    {
        id: 5,
        name: 'Hajj n Ummra Services',
        Category: 'Hajj n Ummra',
        image : '../images/Portfolio05.png',
        desc : 'Want to go for Ummra/Hajj ?',
    },
    {
        id: 6,
        name: 'Supermarts Services',
        Category: 'Supermarts',
        image : '../images/Portfolio06.jpg',
        desc : 'Looking for Supermarts ?',
    },
    {
        id: 7,
        name: 'Rent A Car Services',
        Category: 'Rent A Car',
        image : '../images/Portfolio07.png',
        desc : 'Need A Car for tour ?',
    },
    {
        id: 8,
        name: 'SEO (Search Engin Optimization) Services',
        Category: 'SEo',
        image : '../images/Portfolio08.png',
        desc : 'Need An SEO Expert ?',
    },
    {
        id: 9,
        name: 'Restaurants Services',
        Category: 'Restaurants',
        image : '../images/Portfolio09.png',
        desc : 'Looking for Restaurants ?',
    },
    {
        id: 10,
        name: 'AC Repair Services',
        Category: 'AC Repair',
        image : '../images/Portfolio10.jpg',
        desc : 'Need An AC Repair Person ?',
    },
    {
        id: 11,
        name: 'Clinics Doctor Services',
        Category: 'Clinics Doctors',
        image : '../images/Portfolio11.jpg',
        desc : 'Need A Clinic Doctors ?',
    },
    {
        id: 12,
        name: 'Courier Services',
        Category: 'Courier',
        image : '../images/Portfolio12.jpg',
        desc : 'Need A Courier ?',
    },
    {
        id: 13,
        name: 'Security Services',
        Category: 'Security',
        image : '../images/Portfolio13.jpg',
        desc : 'Need A Security Person ?',
    },
    {
        id: 14,
        name: 'Graphic Designer Services',
        Category: 'Graphic Designers',
        image : '../images/Portfolio14.png',
        desc : 'Need A Graphic Designer ?',
    },
    {
        id: 15,
        name: 'Bus Services',
        Category: 'Buses',
        image : '../images/Portfolio15.jpg',
        desc : 'Need A Bus For Tour ?',
    },
    {
        id: 16,
        name: 'Wifi Provider Services',
        Category: 'Wifi Provider',
        image : '../images/Portfolio16.png',
        desc : 'Need A Wifi Provider ?',
    },
    {
        id: 17,
        name: 'Fruit Shops ',
        Category: 'Fruit Shops',
        image : '../images/Portfolio17.jfif',
        desc : 'Looking for Fruit Shops ?',
    },
    {
        id: 18,
        name: 'Digital Printing Services',
        Category: 'Electrician',
        image : '../images/Portfolio19.png',
        desc : 'Need A Digital Printing Services ?',
    },
    {
        id: 19,
        name: 'Labour Services',
        Category: 'Labours',
        image : '../images/Portfolio19.png',
        desc : 'Looking for Labour Services for Help ?',
    },
    {
        id: 20,
        name: 'Pakistan Post Services',
        Category: 'Pakistan Post',
        image : '../images/Portfolio20.jpg',
        desc : 'Looking for Pakistan Post Couriers ?',
    },
    {
        id: 21,
        name: 'Plumber Services',
        Category: 'Plumber',
        image : '../images/Portfolio21.jpg',
        desc : 'Need An Plumber ?',
    },
    {
        id: 22,
        name: 'Web Developers',
        Category: 'Web Developers',
        image : '../images/Portfolio22.jpg',
        desc : 'Need A Web Developers ?',
    },
]

export default CategoriesUiData;